version: "3.8"

services:
  sensor-server:
    build:
      context: ./sensor_server # Path to the Spring Boot app Dockerfile
      dockerfile: Dockerfile
    container_name: sensor-server
    ports:
      - "8081:8081"
    networks:
      - sensor-network
    env_file:
      - ./sensor_server/.env

  sensor-client:
    build:
      context: ./sensorNode # Path to the Java console app Dockerfile
      dockerfile: Dockerfile
    container_name: sensor-client
    depends_on:
      - sensor-server
    environment:
      - SERVER_URL=ws://sensor-server:8081/sensor
    networks:
      - sensor-network
    restart: always

networks:
  sensor-network:
    driver: bridge
