services:
  - type: web
    runtime: docker
    name: sensor-server
    image:
      url: docker.io/mihir2109/sensor_data-sensor-server
    plan: free

  - type: web
    runtime: docker
    name: sensor-client
    image:
      url: docker.io/mihir2109/sensor_data-sensor-client
    plan: free
    envVars:
      - key: SERVER_URL
        value: ws://sensor-server:8081/sensor
